BEGIN;

ALTER TABLE user_profiles
  ADD COLUMN IF NOT EXISTS auto_recharge_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS auto_recharge_threshold INTEGER NOT NULL DEFAULT 100,
  ADD COLUMN IF NOT EXISTS auto_recharge_quantity INTEGER NOT NULL DEFAULT 1000;

COMMIT;
