#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FRONTEND_DIR="${ROOT_DIR}/frontend"
API_DIR="${ROOT_DIR}/api"
API_DEV_VARS_FILE="${API_DIR}/.dev.vars"
ENV_FILE="${CERUL_ENV_FILE:-${ROOT_DIR}/.env}"

FRONTEND_HOST="${FRONTEND_HOST:-127.0.0.1}"
FRONTEND_PORT="${FRONTEND_PORT:-}"
API_HOST="${API_HOST:-127.0.0.1}"
API_PORT="${API_PORT:-}"

public_host_for_url() {
  local host="$1"

  case "${host}" in
    ""|"0.0.0.0"|"::"|"[::]")
      echo "127.0.0.1"
      return 0
      ;;
    *:*)
      if [[ "${host}" == \[*\] ]]; then
        echo "${host}"
      else
        echo "[${host}]"
      fi
      return 0
      ;;
    *)
      echo "${host}"
      return 0
      ;;
  esac
}

load_env() {
  if [ -f "${ENV_FILE}" ]; then
    set -a
    . "${ENV_FILE}"
    set +a
  fi

  FRONTEND_PORT="${FRONTEND_PORT:-${WEB_PORT:-3000}}"
  API_PORT="${API_PORT:-8787}"

  export CERUL_ENV="${CERUL_ENV:-development}"
  export DEMO_MODE="${DEMO_MODE:-true}"

  local default_web_base_url="http://$(public_host_for_url "${FRONTEND_HOST}"):${FRONTEND_PORT}"
  local default_api_base_url="http://$(public_host_for_url "${API_HOST}"):${API_PORT}"

  export WEB_BASE_URL="${WEB_BASE_URL:-${NEXT_PUBLIC_SITE_URL:-${default_web_base_url}}}"
  export NEXT_PUBLIC_SITE_URL="${NEXT_PUBLIC_SITE_URL:-${WEB_BASE_URL}}"
  export API_BASE_URL="${API_BASE_URL:-${NEXT_PUBLIC_API_BASE_URL:-${default_api_base_url}}}"
  export NEXT_PUBLIC_API_BASE_URL="${NEXT_PUBLIC_API_BASE_URL:-${API_BASE_URL}}"
}

require_command() {
  local name="$1"

  if ! command -v "$name" >/dev/null 2>&1; then
    echo "[dev] Missing required command: ${name}" >&2
    exit 1
  fi
}

require_frontend_package_manager() {
  if command -v corepack >/dev/null 2>&1; then
    return 0
  fi

  require_command pnpm
}

write_dev_var() {
  local key="$1"

  if [ "${!key+x}" != "x" ]; then
    return 0
  fi

  local value="${!key}"

  value="${value//$'\r'/}"
  value="${value//$'\n'/\\n}"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"

  printf '%s="%s"\n' "${key}" "${value}" >> "${API_DEV_VARS_FILE}"
}

sync_api_dev_vars() {
  cat > "${API_DEV_VARS_FILE}" <<EOF
# Generated by scripts/dev.sh from ${ENV_FILE}
# Do not edit by hand; update ${ENV_FILE} instead.
EOF

  local keys=(
    CERUL_ENV
    API_BASE_URL
    WEB_BASE_URL
    NEXT_PUBLIC_API_BASE_URL
    NEXT_PUBLIC_SITE_URL
    DEMO_MODE
    EMBEDDING_BACKEND
    EMBEDDING_MODEL
    EMBEDDING_DIMENSION
    EMBEDDING_NORMALIZE
    EMBEDDING_OPENAI_BASE_URL
    EMBEDDING_OPENAI_API_KEY
    EMBEDDING_OPENAI_MODEL
    RERANK_MODEL
    R2_BUCKET_NAME
    R2_PUBLIC_URL
    DATABASE_URL
    BETTER_AUTH_SECRET
    ADMIN_CONSOLE_EMAILS
    OPENAI_API_KEY
    GEMINI_API_KEY
    JINA_API_KEY
    STRIPE_SECRET_KEY
    STRIPE_WEBHOOK_SECRET
    STRIPE_MONTHLY_PRICE_ID
    STRIPE_TOPUP_1000_PRICE_ID
    STRIPE_TOPUP_5000_PRICE_ID
    STRIPE_TOPUP_20000_PRICE_ID
    YOUTUBE_API_KEY
    PEXELS_API_KEY
    PIXABAY_API_KEY
  )

  local key
  for key in "${keys[@]}"; do
    write_dev_var "${key}"
  done
}

cleanup() {
  if [ -n "${FRONTEND_PID:-}" ] && kill -0 "${FRONTEND_PID}" >/dev/null 2>&1; then
    kill "${FRONTEND_PID}" >/dev/null 2>&1 || true
  fi

  if [ -n "${API_PID:-}" ] && kill -0 "${API_PID}" >/dev/null 2>&1; then
    kill "${API_PID}" >/dev/null 2>&1 || true
  fi
}

start_api() {
  if [ ! -d "${API_DIR}/node_modules" ]; then
    echo "[dev] API dependencies are missing. Run ./rebuild.sh first." >&2
    exit 1
  fi

  sync_api_dev_vars

  (
    cd "${API_DIR}"
    exec npm run dev -- --env development --ip "${API_HOST}" --port "${API_PORT}"
  ) &
  API_PID=$!
}

start_frontend() {
  (
    if command -v corepack >/dev/null 2>&1; then
      cd "${FRONTEND_DIR}"
      exec corepack pnpm dev --hostname "${FRONTEND_HOST}" --port "${FRONTEND_PORT}"
    fi

    cd "${ROOT_DIR}"
    exec pnpm --dir frontend dev --hostname "${FRONTEND_HOST}" --port "${FRONTEND_PORT}"
  ) &
  FRONTEND_PID=$!
}

watch_processes() {
  while true; do
    if ! kill -0 "${API_PID}" >/dev/null 2>&1; then
      wait "${API_PID}"
      return $?
    fi

    if ! kill -0 "${FRONTEND_PID}" >/dev/null 2>&1; then
      wait "${FRONTEND_PID}"
      return $?
    fi

    sleep 1
  done
}

load_env
require_frontend_package_manager
require_command npm

if [ "${CERUL_LOCAL_INFRA_READY:-0}" != "1" ]; then
  if [ ! -x "${ROOT_DIR}/scripts/ensure-local-infra.sh" ]; then
    echo "[dev] Local infrastructure helper is missing or not executable." >&2
    exit 1
  fi

  "${ROOT_DIR}/scripts/ensure-local-infra.sh" --env-file "${ENV_FILE}"
fi

echo "=========================================="
echo "  Cerul Development Environment"
echo "=========================================="
echo "[dev] env file: ${ENV_FILE}"
echo "[dev] frontend: ${NEXT_PUBLIC_SITE_URL} (bind ${FRONTEND_HOST}:${FRONTEND_PORT})"
echo "[dev] api:      ${NEXT_PUBLIC_API_BASE_URL} (bind ${API_HOST}:${API_PORT})"
echo "[dev] worker:   use ./run-worker.sh separately"
echo ""

trap cleanup EXIT INT TERM

start_api
start_frontend
watch_processes
